# Generated by Django 3.2 on 2021-04-16 09:03

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=main.models.generate_code, max_length=6, unique=True)),
                ('current_players', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Teg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.game')),
            ],
            options={
                'verbose_name_plural': 'tags',
            },
        ),
    ]
