# Generated by Django 3.2 on 2021-04-16 20:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 16, 20, 1, 24, 199252, tzinfo=utc)),
        ),
    ]
