# Generated by Django 3.2 on 2021-04-16 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_teg_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
