# Generated by Django 3.2 on 2021-04-17 17:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210417_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_creator',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='is_over',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 17, 17, 48, 14, 778465, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='games', to='main.Tag'),
        ),
    ]
