# Generated by Django 3.2 on 2021-04-18 17:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210417_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 17, 14, 48, 591631, tzinfo=utc)),
        ),
    ]
